/* ══════════════════════════════════════════════════════════════
   D-SWIFT MALL  |  products-data.js
   Local product catalog — no backend/database involved.
   To add, edit, or remove a product, just edit this array directly.
   Each item needs a unique numeric `id`.
   ══════════════════════════════════════════════════════════════ */

const LOCAL_PRODUCTS = [
    {
        id: 1,
        sellerId: null,
        sellerName: 'D-Swift Mall',
        sellerPhone: null,
        name: 'New Balance 530 Sneakers',
        category: 'Fashion',
        price: 420.00,
        description: 'Classic New Balance 530 running sneakers in white with navy accents. Breathable mesh upper, cushioned sole, true to size.',
        image: '16.jpg',
        extraImages: [],
    },
    {
        id: 2,
        sellerId: null,
        sellerName: 'D-Swift Mall',
        sellerPhone: null,
        name: 'Keep Running Sport Sneakers',
        category: 'Sports',
        price: 260.00,
        description: 'Lightweight red and black running shoes built for daily training — flexible knit upper and a shock-absorbing sole.',
        image: '44.jpg',
        extraImages: [],
    },
    {
        id: 3,
        sellerId: null,
        sellerName: 'D-Swift Mall',
        sellerPhone: null,
        name: 'Smart Fitness Watch',
        category: 'Electronics',
        price: 250.00,
        description: 'Round-face smart watch with heart-rate tracking, step counter, sleep monitoring, and a full-colour touchscreen. Compatible with Android & iOS.',
        image: '37.jpg',
        extraImages: [],
    },
    {
        id: 4,
        sellerId: null,
        sellerName: 'D-Swift Mall',
        sellerPhone: null,
        name: 'RGB Wired Gaming Mouse',
        category: 'Electronics',
        price: 90.00,
        description: '6-button wired gaming mouse with adjustable DPI and customizable RGB lighting. Comfortable ergonomic grip for long sessions.',
        image: '42.jpg',
        extraImages: [],
    },
    {
        id: 5,
        sellerId: null,
        sellerName: 'D-Swift Mall',
        sellerPhone: null,
        name: 'Nivea Creme (60ml Tin)',
        category: 'Beauty',
        price: 28.00,
        description: 'The iconic Nivea Creme in the classic blue tin — a rich, all-purpose moisturizer for face, hands and body.',
        image: '10.jpg',
        extraImages: [],
    },
    {
        id: 6,
        sellerId: null,
        sellerName: 'D-Swift Mall',
        sellerPhone: null,
        name: 'The History of Whoo Gift Set for Men',
        category: 'Beauty',
        price: 980.00,
        description: 'Luxury Korean skincare gift set for men — balancer, emulsion and cleansing foam in an elegant presentation box. Great gift item.',
        image: '19.jpg',
        extraImages: [],
    },
    {
        id: 7,
        sellerId: null,
        sellerName: 'D-Swift Mall',
        sellerPhone: null,
        name: 'Nivea Men Skincare Bundle',
        category: 'Beauty',
        price: 190.00,
        description: 'Full Nivea Men lineup — deodorant, shaving gel, whitening body lotion, facial cleanser and serum — everything for a grooming routine.',
        image: '25.jpg',
        extraImages: [],
    },
    {
        id: 8,
        sellerId: null,
        sellerName: 'D-Swift Mall',
        sellerPhone: null,
        name: 'Nivea Roll-On Deodorant (3-Pack)',
        category: 'Beauty',
        price: 65.00,
        description: 'Set of 3 Nivea roll-on deodorants — Men Deep, Dry Confidence and Black & White Invisible — 48h protection.',
        image: '27.jpg',
        extraImages: [],
    },
    {
        id: 9,
        sellerId: null,
        sellerName: 'D-Swift Mall',
        sellerPhone: null,
        name: 'Mickey Stainless Steel Flask',
        category: 'Home & Kitchen',
        price: 75.00,
        description: 'Insulated stainless steel vacuum flask with a fun Mickey design and carry strap. Keeps drinks hot or cold for hours. Available in 5 colours.',
        image: '11.jpg',
        extraImages: [],
    },
    {
        id: 10,
        sellerId: null,
        sellerName: 'D-Swift Mall',
        sellerPhone: null,
        name: 'LED Temperature Display Flask',
        category: 'Home & Kitchen',
        price: 110.00,
        description: 'Smart vacuum flask with a built-in LED display showing the exact temperature of your drink at a glance.',
        image: '28.jpg',
        extraImages: [],
    },
    {
        id: 11,
        sellerId: null,
        sellerName: 'D-Swift Mall',
        sellerPhone: null,
        name: 'Marble Pattern Vacuum Flask',
        category: 'Home & Kitchen',
        price: 85.00,
        description: '"Enjoy the Sweet" marble-finish stainless steel flask — sleek design, double-wall insulation, leak-proof lid.',
        image: '39.jpg',
        extraImages: [],
    },
];
